### PR TITLE
Merging json_clean branch to dev

### PR DESCRIPTION
**Pull request by Japooter**
Please check the README.md, to see if this is an acceptable change. Also note two files will be added to the dev branch alongside it, though this is not everything we are planning to add to the dev branch from json_clean. There may be python code also included at some point.

### CODE REVIEW

**Review by djclsparta — CHANGES_REQUESTED** [review]
I don't think talent.json should be publicly posted on a git repository

**Comment by Japooter** [comment]
> I don't think talent.json should be publicly posted on a git repository

Shall we not include it in the commit but still reference it within the notebook? Just so that the steps can still be shown

**Comment by djclsparta** [comment]
> > I don't think talent.json should be publicly posted on a git repository
> 
> Shall we not include it in the commit but still reference it within the notebook? Just so that the steps can still be shown

Yes, I think that would be best. The notebook should be able to pull the data from S3, clean it ready to upload to SQL.

**Comment by Japooter** [comment]
> > > I don't think talent.json should be publicly posted on a git repository
> > 
> > 
> > Shall we not include it in the commit but still reference it within the notebook? Just so that the steps can still be shown
> 
> Yes, I think that would be best. The notebook should be able to pull the data from S3, clean it ready to upload to SQL.

This can be done within the notebook upon a further edit. For now I have deleted the talent.json and will make changes to the notebook in the dev branch soon, so long as this is approved.

**Review by djclsparta — APPROVED** [review]

**Review by RajAujla01 — APPROVED** [review]

**Review by RajAujla01 — APPROVED** [review]

**Comment by RajAujla01** [comment]
good stuff

**Review by SamDavidSmith — APPROVED** [review]

**Pull request merged**
